//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeDB2024.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Data.mdf;Inte" +
            "grated Security=True")]
        public string DataConnectionString {
            get {
                return ((string)(this["DataConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAltimeter {
            get {
                return ((bool)(this["UseAltimeter"]));
            }
            set {
                this["UseAltimeter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StdVehicle {
            get {
                return ((string)(this["StdVehicle"]));
            }
            set {
                this["StdVehicle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StdContinent {
            get {
                return ((string)(this["StdContinent"]));
            }
            set {
                this["StdContinent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StdCity {
            get {
                return ((string)(this["StdCity"]));
            }
            set {
                this["StdCity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StdRoute {
            get {
                return ((string)(this["StdRoute"]));
            }
            set {
                this["StdRoute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 500")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GoogleEarth {
            get {
                return ((string)(this["GoogleEarth"]));
            }
            set {
                this["GoogleEarth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StdCountry {
            get {
                return ((string)(this["StdCountry"]));
            }
            set {
                this["StdCountry"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StdBundesland {
            get {
                return ((string)(this["StdBundesland"]));
            }
            set {
                this["StdBundesland"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowToolbar {
            get {
                return ((bool)(this["ShowToolbar"]));
            }
            set {
                this["ShowToolbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHelp {
            get {
                return ((bool)(this["ShowHelp"]));
            }
            set {
                this["ShowHelp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageFolder {
            get {
                return ((string)(this["ImageFolder"]));
            }
            set {
                this["ImageFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point HelpLocation {
            get {
                return ((global::System.Drawing.Point)(this["HelpLocation"]));
            }
            set {
                this["HelpLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 400")]
        public global::System.Drawing.Size HelpSize {
            get {
                return ((global::System.Drawing.Size)(this["HelpSize"]));
            }
            set {
                this["HelpSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50, 50")]
        public global::System.Drawing.Point StatLocation {
            get {
                return ((global::System.Drawing.Point)(this["StatLocation"]));
            }
            set {
                this["StatLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 400")]
        public global::System.Drawing.Size StatSize {
            get {
                return ((global::System.Drawing.Size)(this["StatSize"]));
            }
            set {
                this["StatSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4, 0")]
        public global::System.Drawing.Point ToolbarLocation {
            get {
                return ((global::System.Drawing.Point)(this["ToolbarLocation"]));
            }
            set {
                this["ToolbarLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("423, 25")]
        public global::System.Drawing.Size ToolbarSize {
            get {
                return ((global::System.Drawing.Size)(this["ToolbarSize"]));
            }
            set {
                this["ToolbarSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 150")]
        public global::System.Drawing.Point ImageViewerLocation {
            get {
                return ((global::System.Drawing.Point)(this["ImageViewerLocation"]));
            }
            set {
                this["ImageViewerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("750, 600")]
        public global::System.Drawing.Size ImageViewerSize {
            get {
                return ((global::System.Drawing.Size)(this["ImageViewerSize"]));
            }
            set {
                this["ImageViewerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point EntfaltungLocation {
            get {
                return ((global::System.Drawing.Point)(this["EntfaltungLocation"]));
            }
            set {
                this["EntfaltungLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 400")]
        public global::System.Drawing.Size EntfaltungSize {
            get {
                return ((global::System.Drawing.Size)(this["EntfaltungSize"]));
            }
            set {
                this["EntfaltungSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWelcomeForm {
            get {
                return ((bool)(this["ShowWelcomeForm"]));
            }
            set {
                this["ShowWelcomeForm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageEditorPath {
            get {
                return ((string)(this["ImageEditorPath"]));
            }
            set {
                this["ImageEditorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImageEditorName {
            get {
                return ((string)(this["ImageEditorName"]));
            }
            set {
                this["ImageEditorName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsMultiUser {
            get {
                return ((bool)(this["IsMultiUser"]));
            }
            set {
                this["IsMultiUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUser {
            get {
                return ((string)(this["LastUser"]));
            }
            set {
                this["LastUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLastUser {
            get {
                return ((bool)(this["ShowLastUser"]));
            }
            set {
                this["ShowLastUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KeepLoggedIn {
            get {
                return ((bool)(this["KeepLoggedIn"]));
            }
            set {
                this["KeepLoggedIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdminChanged {
            get {
                return ((bool)(this["AdminChanged"]));
            }
            set {
                this["AdminChanged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowBirthdays {
            get {
                return ((bool)(this["ShowBirthdays"]));
            }
            set {
                this["ShowBirthdays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UserLoggedIn {
            get {
                return ((bool)(this["UserLoggedIn"]));
            }
            set {
                this["UserLoggedIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdminLoggedIn {
            get {
                return ((bool)(this["AdminLoggedIn"]));
            }
            set {
                this["AdminLoggedIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentUserID {
            get {
                return ((int)(this["CurrentUserID"]));
            }
            set {
                this["CurrentUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentUserName {
            get {
                return ((string)(this["CurrentUserName"]));
            }
            set {
                this["CurrentUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point AdminLocation {
            get {
                return ((global::System.Drawing.Point)(this["AdminLocation"]));
            }
            set {
                this["AdminLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 500")]
        public global::System.Drawing.Size AdminSize {
            get {
                return ((global::System.Drawing.Size)(this["AdminSize"]));
            }
            set {
                this["AdminSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MinPasswordLength {
            get {
                return ((int)(this["MinPasswordLength"]));
            }
            set {
                this["MinPasswordLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowNotifyIcon {
            get {
                return ((bool)(this["ShowNotifyIcon"]));
            }
            set {
                this["ShowNotifyIcon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int NotifyTime {
            get {
                return ((int)(this["NotifyTime"]));
            }
            set {
                this["NotifyTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InstallationType {
            get {
                return ((string)(this["InstallationType"]));
            }
            set {
                this["InstallationType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFlightDB {
            get {
                return ((bool)(this["ShowFlightDB"]));
            }
            set {
                this["ShowFlightDB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point FlightDBLocation {
            get {
                return ((global::System.Drawing.Point)(this["FlightDBLocation"]));
            }
            set {
                this["FlightDBLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 500")]
        public global::System.Drawing.Size FlightDBSize {
            get {
                return ((global::System.Drawing.Size)(this["FlightDBSize"]));
            }
            set {
                this["FlightDBSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseSigmaDockingStation {
            get {
                return ((bool)(this["UseSigmaDockingStation"]));
            }
            set {
                this["UseSigmaDockingStation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseAdminSettings {
            get {
                return ((bool)(this["UseAdminSettings"]));
            }
            set {
                this["UseAdminSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GpxFolder {
            get {
                return ((string)(this["GpxFolder"]));
            }
            set {
                this["GpxFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80, 80")]
        public global::System.Drawing.Point ImageGalleryLocation {
            get {
                return ((global::System.Drawing.Point)(this["ImageGalleryLocation"]));
            }
            set {
                this["ImageGalleryLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 500")]
        public global::System.Drawing.Size ImageGallerySize {
            get {
                return ((global::System.Drawing.Size)(this["ImageGallerySize"]));
            }
            set {
                this["ImageGallerySize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImageViewer")]
        public string ImageGalleryViewer {
            get {
                return ((string)(this["ImageGalleryViewer"]));
            }
            set {
                this["ImageGalleryViewer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte ThumbnailSize {
            get {
                return ((byte)(this["ThumbnailSize"]));
            }
            set {
                this["ThumbnailSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GPSCoordAngle {
            get {
                return ((bool)(this["GPSCoordAngle"]));
            }
            set {
                this["GPSCoordAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FDBAirportSetting {
            get {
                return ((int)(this["FDBAirportSetting"]));
            }
            set {
                this["FDBAirportSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FDBAirlineSetting {
            get {
                return ((int)(this["FDBAirlineSetting"]));
            }
            set {
                this["FDBAirlineSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int FDBPlaneSetting {
            get {
                return ((int)(this["FDBPlaneSetting"]));
            }
            set {
                this["FDBPlaneSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Economy")]
        public string FDBClassSetting {
            get {
                return ((string)(this["FDBClassSetting"]));
            }
            set {
                this["FDBClassSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int FDBTakeOffSetting {
            get {
                return ((int)(this["FDBTakeOffSetting"]));
            }
            set {
                this["FDBTakeOffSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int FDBLandingSetting {
            get {
                return ((int)(this["FDBLandingSetting"]));
            }
            set {
                this["FDBLandingSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FDBStartTypeSetting {
            get {
                return ((int)(this["FDBStartTypeSetting"]));
            }
            set {
                this["FDBStartTypeSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FDBStartSetting {
            get {
                return ((string)(this["FDBStartSetting"]));
            }
            set {
                this["FDBStartSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FDBZoomSetting {
            get {
                return ((int)(this["FDBZoomSetting"]));
            }
            set {
                this["FDBZoomSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("280")]
        public int FDBSplitterSetting {
            get {
                return ((int)(this["FDBSplitterSetting"]));
            }
            set {
                this["FDBSplitterSetting"] = value;
            }
        }
    }
}
